/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CheckoutSession } from '../models';
import { CheckoutSessionCreationParams } from '../models';
/**
 * CheckoutsApi - axios parameter creator
 * @export
 */
export const CheckoutsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a checkout session by supplying the correct parameters. When a customer pays on the checkout session an order will be created.
         * @summary Create a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCheckout: async (body: CheckoutSessionCreationParams, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createCheckout.');
            }
            const localVarPath = `/checkouts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication merchant-api-key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("x-api-key")
                    : await configuration.apiKey;
                localVarHeaderParameter["x-api-key"] = localVarApiKeyValue;
            }

            // authentication merchant-jwt required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Supply the unique dispute ID and receive corresponding checkout details.
         * @summary Retrieve a checkout session
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCheckout: async (checkoutId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'checkoutId' is not null or undefined
            if (checkoutId === null || checkoutId === undefined) {
                throw new RequiredError('checkoutId','Required parameter checkoutId was null or undefined when calling getCheckout.');
            }
            const localVarPath = `/checkouts/{checkoutId}`
                .replace(`{${"checkoutId"}}`, encodeURIComponent(String(checkoutId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication merchant-api-key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("x-api-key")
                    : await configuration.apiKey;
                localVarHeaderParameter["x-api-key"] = localVarApiKeyValue;
            }

            // authentication merchant-jwt required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of checkout sessions by supplying the correct parameters.
         * @summary List all checkout sessions
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCheckouts: async (pageNum?: number, pageSize?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/checkouts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication merchant-api-key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("x-api-key")
                    : await configuration.apiKey;
                localVarHeaderParameter["x-api-key"] = localVarApiKeyValue;
            }

            // authentication merchant-jwt required

            if (pageNum !== undefined) {
                localVarQueryParameter['pageNum'] = pageNum;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update a checkout session by supplying the correct parameters.
         * @summary Update a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCheckout: async (body: CheckoutSessionCreationParams, checkoutId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateCheckout.');
            }
            // verify required parameter 'checkoutId' is not null or undefined
            if (checkoutId === null || checkoutId === undefined) {
                throw new RequiredError('checkoutId','Required parameter checkoutId was null or undefined when calling updateCheckout.');
            }
            const localVarPath = `/checkouts/{checkoutId}`
                .replace(`{${"checkoutId"}}`, encodeURIComponent(String(checkoutId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication merchant-api-key required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("x-api-key")
                    : await configuration.apiKey;
                localVarHeaderParameter["x-api-key"] = localVarApiKeyValue;
            }

            // authentication merchant-jwt required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CheckoutsApi - functional programming interface
 * @export
 */
export const CheckoutsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Create a checkout session by supplying the correct parameters. When a customer pays on the checkout session an order will be created.
         * @summary Create a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCheckout(body: CheckoutSessionCreationParams, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CheckoutSession>>> {
            const localVarAxiosArgs = await CheckoutsApiAxiosParamCreator(configuration).createCheckout(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Supply the unique dispute ID and receive corresponding checkout details.
         * @summary Retrieve a checkout session
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCheckout(checkoutId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CheckoutSession>>> {
            const localVarAxiosArgs = await CheckoutsApiAxiosParamCreator(configuration).getCheckout(checkoutId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieve a list of checkout sessions by supplying the correct parameters.
         * @summary List all checkout sessions
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCheckouts(pageNum?: number, pageSize?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CheckoutSession>>>> {
            const localVarAxiosArgs = await CheckoutsApiAxiosParamCreator(configuration).listCheckouts(pageNum, pageSize, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update a checkout session by supplying the correct parameters.
         * @summary Update a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCheckout(body: CheckoutSessionCreationParams, checkoutId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CheckoutSession>>> {
            const localVarAxiosArgs = await CheckoutsApiAxiosParamCreator(configuration).updateCheckout(body, checkoutId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CheckoutsApi - factory interface
 * @export
 */
export const CheckoutsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Create a checkout session by supplying the correct parameters. When a customer pays on the checkout session an order will be created.
         * @summary Create a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCheckout(body: CheckoutSessionCreationParams, options?: AxiosRequestConfig): Promise<AxiosResponse<CheckoutSession>> {
            return CheckoutsApiFp(configuration).createCheckout(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Supply the unique dispute ID and receive corresponding checkout details.
         * @summary Retrieve a checkout session
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCheckout(checkoutId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CheckoutSession>> {
            return CheckoutsApiFp(configuration).getCheckout(checkoutId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of checkout sessions by supplying the correct parameters.
         * @summary List all checkout sessions
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCheckouts(pageNum?: number, pageSize?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CheckoutSession>>> {
            return CheckoutsApiFp(configuration).listCheckouts(pageNum, pageSize, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Update a checkout session by supplying the correct parameters.
         * @summary Update a checkout session
         * @param {CheckoutSessionCreationParams} body 
         * @param {string} checkoutId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCheckout(body: CheckoutSessionCreationParams, checkoutId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CheckoutSession>> {
            return CheckoutsApiFp(configuration).updateCheckout(body, checkoutId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CheckoutsApi - object-oriented interface
 * @export
 * @class CheckoutsApi
 * @extends {BaseAPI}
 */
export class CheckoutsApi extends BaseAPI {
    /**
     * Create a checkout session by supplying the correct parameters. When a customer pays on the checkout session an order will be created.
     * @summary Create a checkout session
     * @param {CheckoutSessionCreationParams} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CheckoutsApi
     */
    public async createCheckout(body: CheckoutSessionCreationParams, options?: AxiosRequestConfig) : Promise<AxiosResponse<CheckoutSession>> {
        return CheckoutsApiFp(this.configuration).createCheckout(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Supply the unique dispute ID and receive corresponding checkout details.
     * @summary Retrieve a checkout session
     * @param {string} checkoutId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CheckoutsApi
     */
    public async getCheckout(checkoutId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CheckoutSession>> {
        return CheckoutsApiFp(this.configuration).getCheckout(checkoutId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieve a list of checkout sessions by supplying the correct parameters.
     * @summary List all checkout sessions
     * @param {number} [pageNum] 
     * @param {number} [pageSize] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CheckoutsApi
     */
    public async listCheckouts(pageNum?: number, pageSize?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CheckoutSession>>> {
        return CheckoutsApiFp(this.configuration).listCheckouts(pageNum, pageSize, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update a checkout session by supplying the correct parameters.
     * @summary Update a checkout session
     * @param {CheckoutSessionCreationParams} body 
     * @param {string} checkoutId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CheckoutsApi
     */
    public async updateCheckout(body: CheckoutSessionCreationParams, checkoutId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CheckoutSession>> {
        return CheckoutsApiFp(this.configuration).updateCheckout(body, checkoutId, options).then((request) => request(this.axios, this.basePath));
    }
}
