/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ACHDetails } from './achdetails';
import { PaymentError } from './payment-error';
/**
 * 
 * @export
 * @interface BankAccountPaymentDetails
 */
export interface BankAccountPaymentDetails {
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    transferType?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    accountOwnershipType?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountPaymentDetails
     */
    statementDescription?: string;
    /**
     * 
     * @type {ACHDetails}
     * @memberof BankAccountPaymentDetails
     */
    achDetails?: ACHDetails;
    /**
     * 
     * @type {Array<PaymentError>}
     * @memberof BankAccountPaymentDetails
     */
    errors?: Array<PaymentError>;
}
