/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AVSStatus } from './avsstatus';
import { CVVStatus } from './cvvstatus';
import { CardDetails } from './card-details';
import { CardPaymentTimeline } from './card-payment-timeline';
import { CardVerificationMethod } from './card-verification-method';
import { CardVerificationResult } from './card-verification-result';
import { DeviceDetails } from './device-details';
import { PaymentError } from './payment-error';
/**
 * 
 * @export
 * @interface CardPaymentDetails
 */
export interface CardPaymentDetails {
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    status?: string;
    /**
     * 
     * @type {CardDetails}
     * @memberof CardPaymentDetails
     */
    card?: CardDetails;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    entryMethod?: string;
    /**
     * 
     * @type {CVVStatus}
     * @memberof CardPaymentDetails
     */
    cvvStatus?: CVVStatus;
    /**
     * 
     * @type {AVSStatus}
     * @memberof CardPaymentDetails
     */
    avsStatus?: AVSStatus;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    authResultCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    applicationIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    applicationName?: string;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    applicationCryptogram?: string;
    /**
     * 
     * @type {CardVerificationMethod}
     * @memberof CardPaymentDetails
     */
    verificationMethod?: CardVerificationMethod;
    /**
     * 
     * @type {CardVerificationResult}
     * @memberof CardPaymentDetails
     */
    verificationResults?: CardVerificationResult;
    /**
     * 
     * @type {string}
     * @memberof CardPaymentDetails
     */
    statementDescription?: string;
    /**
     * 
     * @type {DeviceDetails}
     * @memberof CardPaymentDetails
     */
    deviceDetails?: DeviceDetails;
    /**
     * 
     * @type {CardPaymentTimeline}
     * @memberof CardPaymentDetails
     */
    cardPaymentTimeline?: CardPaymentTimeline;
    /**
     * 
     * @type {boolean}
     * @memberof CardPaymentDetails
     */
    refundRequiresCardPresence?: boolean;
    /**
     * Information about errors encountered during the request.
     * @type {Array<PaymentError>}
     * @memberof CardPaymentDetails
     */
    errors?: Array<PaymentError>;
}
