/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CardBrand } from './card-brand';
import { ModelInteger } from './model-integer';
/**
 * 
 * @export
 * @interface CardDetails
 */
export interface CardDetails {
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    id: string;
    /**
     * 
     * @type {CardBrand}
     * @memberof CardDetails
     */
    cardBrand: CardBrand;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    last4?: string;
    /**
     * 
     * @type {ModelInteger}
     * @memberof CardDetails
     */
    expMonth?: ModelInteger;
    /**
     * 
     * @type {ModelInteger}
     * @memberof CardDetails
     */
    expYear?: ModelInteger;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    cardholderName?: string;
    /**
     * 
     * @type {Address}
     * @memberof CardDetails
     */
    billingAddress?: Address;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    referenceId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CardDetails
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    cardType?: string;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    prepaidType?: string;
    /**
     * 
     * @type {string}
     * @memberof CardDetails
     */
    bin?: string;
}
