/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CheckoutLineItemCreationParam } from './checkout-line-item-creation-param';
import { CheckoutPageOptions } from './checkout-page-options';
import { CustomerCreationParams } from './customer-creation-params';
import { MetaData } from './meta-data';
/**
 * 
 * @export
 * @interface CheckoutSessionCreationParams
 */
export interface CheckoutSessionCreationParams {
    /**
     * 
     * @type {Array<CheckoutLineItemCreationParam>}
     * @memberof CheckoutSessionCreationParams
     */
    lineItemParams: Array<CheckoutLineItemCreationParam>;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreationParams
     */
    referenceId?: string;
    /**
     * 
     * @type {CustomerCreationParams | string}
     * @memberof CheckoutSessionCreationParams
     */
    customer?: CustomerCreationParams | string;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionCreationParams
     */
    expirationDate?: Date;
    /**
     * 
     * @type {CheckoutPageOptions}
     * @memberof CheckoutSessionCreationParams
     */
    checkoutPageOptions: CheckoutPageOptions;
    /**
     * 
     * @type {MetaData}
     * @memberof CheckoutSessionCreationParams
     */
    metaData?: MetaData;
}
