/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CustomAllocations } from './custom-allocations';
import { CustomerCreationParams } from './customer-creation-params';
import { ItemAllocations } from './item-allocations';
import { Money } from './money';
import { SplitType } from './split-type';
/**
 * 
 * @export
 * @interface CreateGroupPaymentRequest
 */
export interface CreateGroupPaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    idempotencyKey: string;
    /**
     * Can either be a customerId or customer object
     * @type {string | CustomerCreationParams}
     * @memberof CreateGroupPaymentRequest
     */
    customer: string | CustomerCreationParams;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    groupId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    checkoutId?: string;
    /**
     * 
     * @type {SplitType}
     * @memberof CreateGroupPaymentRequest
     */
    splitType?: SplitType;
    /**
     * 
     * @type {number}
     * @memberof CreateGroupPaymentRequest
     */
    splitAllocation?: number;
    /**
     * 
     * @type {CustomAllocations}
     * @memberof CreateGroupPaymentRequest
     */
    customAllocation?: CustomAllocations;
    /**
     * 
     * @type {ItemAllocations}
     * @memberof CreateGroupPaymentRequest
     */
    itemAllocation?: ItemAllocations;
    /**
     * 
     * @type {Money}
     * @memberof CreateGroupPaymentRequest
     */
    amountMoney: Money;
    /**
     * 
     * @type {Money}
     * @memberof CreateGroupPaymentRequest
     */
    tipMoney?: Money;
    /**
     * 
     * @type {Date}
     * @memberof CreateGroupPaymentRequest
     */
    expirationDate?: Date;
    /**
     * 
     * @type {Address}
     * @memberof CreateGroupPaymentRequest
     */
    shippingAddress?: Address;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    statementDescriptionIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupPaymentRequest
     */
    referenceId?: string;
}
