/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Money } from './money';
/**
 * 
 * @export
 * @interface CreatePaymentRequest
 */
export interface CreatePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    idempotencyKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    paymentToken: string;
    /**
     * 
     * @type {Money}
     * @memberof CreatePaymentRequest
     */
    amountMoney: Money;
    /**
     * 
     * @type {Money}
     * @memberof CreatePaymentRequest
     */
    tipMoney?: Money;
    /**
     * 
     * @type {Money}
     * @memberof CreatePaymentRequest
     */
    sellerFee?: Money;
    /**
     * 
     * @type {Address}
     * @memberof CreatePaymentRequest
     */
    billingAddress?: Address;
    /**
     * 
     * @type {Address}
     * @memberof CreatePaymentRequest
     */
    shippingAddress?: Address;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePaymentRequest
     */
    autocomplete?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreatePaymentRequest
     */
    expirationDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    verificationToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    statementDescriptionIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    referenceId?: string;
}
