/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { EmailAddress } from './email-address';
import { Url } from './url';
/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    lastName?: string;
    /**
     * 
     * @type {EmailAddress}
     * @memberof Customer
     */
    email: EmailAddress;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Url}
     * @memberof Customer
     */
    imageUrl?: Url;
    /**
     * 
     * @type {Address}
     * @memberof Customer
     */
    address?: Address;
    /**
     * 
     * @type {string}
     * @memberof Customer
     */
    language?: string;
    /**
     * 
     * @type {Date}
     * @memberof Customer
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Customer
     */
    updatedAt?: Date;
}
