/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailAddress } from './email-address';
/**
 * 
 * @export
 * @interface CustomerCreationParams
 */
export interface CustomerCreationParams {
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationParams
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationParams
     */
    lastName?: string;
    /**
     * 
     * @type {EmailAddress}
     * @memberof CustomerCreationParams
     */
    email: EmailAddress;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationParams
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreationParams
     */
    language?: string;
}
