/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CardBrand } from './card-brand';
import { DisputeReason } from './dispute-reason';
import { DisputeStatus } from './dispute-status';
import { Money } from './money';
/**
 * 
 * @export
 * @interface Dispute
 */
export interface Dispute {
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    paymentId: string;
    /**
     * 
     * @type {Money}
     * @memberof Dispute
     */
    amountMoney: Money;
    /**
     * 
     * @type {DisputeReason}
     * @memberof Dispute
     */
    reason: DisputeReason;
    /**
     * 
     * @type {DisputeStatus}
     * @memberof Dispute
     */
    status: DisputeStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof Dispute
     */
    evidenceIds?: Array<string>;
    /**
     * 
     * @type {CardBrand}
     * @memberof Dispute
     */
    cardBrand?: CardBrand;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    brandDisputeId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Dispute
     */
    dueAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Dispute
     */
    reportedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    locationId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Dispute
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Dispute
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Dispute
     */
    version?: number;
}
