/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attributes } from './attributes';
import { ItemCreationParamsInventoryDetails } from './item-creation-params-inventory-details';
import { ItemCreationParamsOrderDetails } from './item-creation-params-order-details';
import { MetaData } from './meta-data';
import { Money } from './money';
import { Url } from './url';
/**
 * 
 * @export
 * @interface ItemCreationParams
 */
export interface ItemCreationParams {
    /**
     * 
     * @type {string}
     * @memberof ItemCreationParams
     */
    sku?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemCreationParams
     */
    name: string;
    /**
     * 
     * @type {Money}
     * @memberof ItemCreationParams
     */
    amountMoney: Money;
    /**
     * 
     * @type {Attributes}
     * @memberof ItemCreationParams
     */
    attributes?: Attributes;
    /**
     * Max of 10 images per item. The first will always be the default.
     * @type {Array<Url>}
     * @memberof ItemCreationParams
     */
    imageUrls?: Array<Url>;
    /**
     * 
     * @type {string}
     * @memberof ItemCreationParams
     */
    description?: string;
    /**
     * 
     * @type {ItemCreationParamsOrderDetails}
     * @memberof ItemCreationParams
     */
    orderDetails?: ItemCreationParamsOrderDetails;
    /**
     * 
     * @type {ItemCreationParamsInventoryDetails}
     * @memberof ItemCreationParams
     */
    inventoryDetails?: ItemCreationParamsInventoryDetails;
    /**
     * 
     * @type {MetaData}
     * @memberof ItemCreationParams
     */
    metaData?: MetaData;
    /**
     * 
     * @type {string}
     * @memberof ItemCreationParams
     */
    referenceId?: string;
}
