/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelInteger } from './model-integer';
import { Money } from './money';
import { PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_ } from './pick-item-or-amount-money-or-attributes-or-description-or-id-or-meta-data-or-image-urls-or-name-or-sku-or-order-details_';
import { Tax } from './tax';
/**
 * 
 * @export
 * @interface LineItem
 */
export interface LineItem {
    /**
     * 
     * @type {PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_}
     * @memberof LineItem
     */
    item: PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_;
    /**
     * 
     * @type {ModelInteger}
     * @memberof LineItem
     */
    quantity: ModelInteger;
    /**
     * 
     * @type {Money}
     * @memberof LineItem
     */
    taxAmount?: Money;
    /**
     * 
     * @type {Array<Tax>}
     * @memberof LineItem
     */
    taxes?: Array<Tax>;
    /**
     * 
     * @type {Money}
     * @memberof LineItem
     */
    subtotalAmount: Money;
    /**
     * 
     * @type {Money}
     * @memberof LineItem
     */
    totalAmount: Money;
}
