/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { InvitedMembers } from './invited-members';
import { Members } from './members';
import { MerchantApiKeySummary } from './merchant-api-key-summary';
import { MerchantContactDetails } from './merchant-contact-details';
/**
 * 
 * @export
 * @interface MerchantDTO
 */
export interface MerchantDTO {
    /**
     * 
     * @type {string}
     * @memberof MerchantDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantDTO
     */
    logoUrl?: string;
    /**
     * 
     * @type {MerchantContactDetails}
     * @memberof MerchantDTO
     */
    contactDetails: MerchantContactDetails;
    /**
     * 
     * @type {Array<MerchantApiKeySummary>}
     * @memberof MerchantDTO
     */
    liveKeys: Array<MerchantApiKeySummary>;
    /**
     * 
     * @type {Array<MerchantApiKeySummary>}
     * @memberof MerchantDTO
     */
    testKeys: Array<MerchantApiKeySummary>;
    /**
     * 
     * @type {Members}
     * @memberof MerchantDTO
     */
    team: Members;
    /**
     * 
     * @type {InvitedMembers}
     * @memberof MerchantDTO
     */
    invites?: InvitedMembers;
    /**
     * 
     * @type {Currency}
     * @memberof MerchantDTO
     */
    defaultCurrency: Currency;
}
