/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OpenIdAddress } from './open-id-address';
import { Url } from './url';
/**
 * 
 * @export
 * @interface OpenIdIdTokenData
 */
export interface OpenIdIdTokenData {
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    sub: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    preferredUsername?: string;
    /**
     * 
     * @type {Url}
     * @memberof OpenIdIdTokenData
     */
    picture?: Url;
    /**
     * 
     * @type {Url}
     * @memberof OpenIdIdTokenData
     */
    profile?: Url;
    /**
     * 
     * @type {Url}
     * @memberof OpenIdIdTokenData
     */
    website?: Url;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    gender?: OpenIdIdTokenDataGenderEnum;
    /**
     * 
     * @type {Date}
     * @memberof OpenIdIdTokenData
     */
    birthdate?: Date;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    zoneinfo?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    locale?: string;
    /**
     * 
     * @type {Date}
     * @memberof OpenIdIdTokenData
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    phoneNumber?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenIdIdTokenData
     */
    phoneNumberVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenIdIdTokenData
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {OpenIdAddress}
     * @memberof OpenIdIdTokenData
     */
    address?: OpenIdAddress;
    /**
     * 
     * @type {Date}
     * @memberof OpenIdIdTokenData
     */
    authTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    nonce?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    acr?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    amr?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdIdTokenData
     */
    azp?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum OpenIdIdTokenDataGenderEnum {
    Female = 'female',
    Male = 'male'
}

