/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OpenIdAddress
 */
export interface OpenIdAddress {
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    locality: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    streetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof OpenIdAddress
     */
    formatted: string;
}
