/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Discount } from './discount';
import { LineItem } from './line-item';
import { MetaData } from './meta-data';
import { Money } from './money';
import { OrderStatus } from './order-status';
import { Tax } from './tax';
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    id: string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof Order
     */
    status: OrderStatus;
    /**
     * 
     * @type {Array<LineItem>}
     * @memberof Order
     */
    lineItems: Array<LineItem>;
    /**
     * 
     * @type {Money}
     * @memberof Order
     */
    totalMoney: Money;
    /**
     * 
     * @type {Money}
     * @memberof Order
     */
    subtotalMoney: Money;
    /**
     * 
     * @type {Money}
     * @memberof Order
     */
    discountMoney?: Money;
    /**
     * 
     * @type {Money}
     * @memberof Order
     */
    tipMoney?: Money;
    /**
     * 
     * @type {Array<Tax>}
     * @memberof Order
     */
    taxes?: Array<Tax>;
    /**
     * 
     * @type {Array<Discount>}
     * @memberof Order
     */
    discounts?: Array<Discount>;
    /**
     * 
     * @type {Address}
     * @memberof Order
     */
    shippingAddress?: Address;
    /**
     * 
     * @type {MetaData}
     * @memberof Order
     */
    metaData?: MetaData;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    version?: number;
}
