/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { CustomAllocations } from './custom-allocations';
import { ItemAllocations } from './item-allocations';
import { ModelInteger } from './model-integer';
import { Money } from './money';
import { SplitType } from './split-type';
/**
 * Make all properties in T optional
 * @export
 * @interface PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
 */
export interface PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_ {
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    groupId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    checkoutId?: string;
    /**
     * 
     * @type {SplitType}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    splitType?: SplitType;
    /**
     * 
     * @type {ModelInteger}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    splitAllocation?: ModelInteger;
    /**
     * 
     * @type {CustomAllocations}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    customAllocation?: CustomAllocations;
    /**
     * 
     * @type {ItemAllocations}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    itemAllocation?: ItemAllocations;
    /**
     * 
     * @type {Money}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    amountMoney?: Money;
    /**
     * 
     * @type {Date}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    expirationDate?: Date;
    /**
     * 
     * @type {Address}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    shippingAddress?: Address;
    /**
     * If this is set to true, the group payment will be completed as soon as the total amount is made up  Defaults to true.
     * @type {boolean}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    autocomplete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    statementDescriptionIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof PartialOmitGroupPaymentCreationParamsCustomerOrIdempotencyKey_
     */
    referenceId?: string;
}
