/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Currency } from './currency';
import { MerchantContactDetails } from './merchant-contact-details';
import { Url } from './url';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_
 */
export interface PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_ {
    /**
     * 
     * @type {string}
     * @memberof PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_
     */
    name: string;
    /**
     * 
     * @type {Url}
     * @memberof PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_
     */
    logoUrl?: Url;
    /**
     * 
     * @type {MerchantContactDetails}
     * @memberof PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_
     */
    contactDetails: MerchantContactDetails;
    /**
     * 
     * @type {Currency}
     * @memberof PickMerchantNameOrContactDetailsOrLogoUrlOrDefaultCurrency_
     */
    defaultCurrency: Currency;
}
