/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attributes } from './attributes';
import { ItemOrderDetails } from './item-order-details';
import { MetaData } from './meta-data';
import { Money } from './money';
import { Url } from './url';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
 */
export interface PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_ {
    /**
     * 
     * @type {string}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    name: string;
    /**
     * 
     * @type {Money}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    amountMoney: Money;
    /**
     * 
     * @type {Attributes}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    attributes?: Attributes;
    /**
     * 300 word description of the item.
     * @type {string}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    description?: string;
    /**
     * 
     * @type {MetaData}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    metaData?: MetaData;
    /**
     * Max 10 images per item. Default image is the first in array.
     * @type {Array<Url>}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    imageUrls?: Array<Url>;
    /**
     * 
     * @type {string}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    sku?: string;
    /**
     * 
     * @type {ItemOrderDetails}
     * @memberof PickItemOrAmountMoneyOrAttributesOrDescriptionOrIdOrMetaDataOrImageUrlsOrNameOrSkuOrOrderDetails_
     */
    orderDetails?: ItemOrderDetails;
}
