/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Url } from './url';
/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
 */
export interface PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_ {
    /**
     * 
     * @type {string}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    name: string;
    /**
     * 
     * @type {Url}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    logoUrl?: Url;
    /**
     * 
     * @type {Array<string>}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    redirectUris?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    secretKey: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    scopes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PickClientExcludeKeyofClientVerifiedSigOrTrustedSig_
     */
    ownerId?: string;
}
