/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Money } from './money';
import { ProcessingFee } from './processing-fee';
import { RefundStatus } from './refund-status';
/**
 * 
 * @export
 * @interface RefundRecord
 */
export interface RefundRecord {
    /**
     * 
     * @type {string}
     * @memberof RefundRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RefundRecord
     */
    paymentId: string;
    /**
     * 
     * @type {Money}
     * @memberof RefundRecord
     */
    amountMoney: Money;
    /**
     * 
     * @type {Money}
     * @memberof RefundRecord
     */
    appFee?: Money;
    /**
     * 
     * @type {RefundStatus}
     * @memberof RefundRecord
     */
    status: RefundStatus;
    /**
     * 
     * @type {Array<ProcessingFee>}
     * @memberof RefundRecord
     */
    processingFees?: Array<ProcessingFee>;
    /**
     * 
     * @type {string}
     * @memberof RefundRecord
     */
    locationId?: string;
    /**
     * 
     * @type {Date}
     * @memberof RefundRecord
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RefundRecord
     */
    updatedAt?: Date;
}
