/* tslint:disable */
/* eslint-disable */
/**
 * Merchant API
 * The Hands In API is the first and only service that enables users to transact within a group. Our API is heavily orientated around being a RESTful service  that has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, ant utilizes standard HTTP response codes
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from './attachment';
import { EmailAddress } from './email-address';
import { ModelObject } from './model-object';
/**
 * 
 * @export
 * @interface TextEmailCreationParams
 */
export interface TextEmailCreationParams {
    /**
     * 
     * @type {Array<EmailAddress>}
     * @memberof TextEmailCreationParams
     */
    to: Array<EmailAddress>;
    /**
     * 
     * @type {string}
     * @memberof TextEmailCreationParams
     */
    subject: string;
    /**
     * 
     * @type {Array<EmailAddress>}
     * @memberof TextEmailCreationParams
     */
    cc?: Array<EmailAddress>;
    /**
     * 
     * @type {Array<EmailAddress>}
     * @memberof TextEmailCreationParams
     */
    bcc?: Array<EmailAddress>;
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof TextEmailCreationParams
     */
    attachment?: Array<Attachment>;
    /**
     * 
     * @type {string}
     * @memberof TextEmailCreationParams
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof TextEmailCreationParams
     */
    html?: string;
    /**
     * 
     * @type {string}
     * @memberof TextEmailCreationParams
     */
    templateName?: string;
    /**
     * 
     * @type {ModelObject}
     * @memberof TextEmailCreationParams
     */
    variables?: ModelObject;
}
